### ISSUE TITLE
这个怎么用呢，第一次接触，可以指点一下吗

### ISSUE THREAD

**Issue by Cregin** [xiekailian/HotelServer#1]
Thanks

**Comment by Prevalence** [comment]
这个工程是一个酒店互联网预定系统的服务器端，客户端在HotelClient中，是我们小组的一个项目，目前还处于构建阶段，只实现了部分功能，GUI也正在开发中，但是三周后会完全完成。你可以关注我们的构建进程或者提出你相关的建议。
